### ISSUE TITLE
Anonymous Usage Reporting Configuration Won't Save

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#1003]
The Anonymous Usage Reporting consent form upon boot keeps reappearing even after the user applies his or her settings.

(See the debug logs here: https://1drv.ms/u/s!Atsjh-pCpQhZgoNrVqBikiUbij6b1w) 

Syncthing for Android 0.12.2 (ARM64). 
Android 8.x Oreo. 
HTC U11 US-Unlocked.

**Comment by Nutomic** [comment]
There is something wrong with your log file, I can't open it. Maybe post it as [gist](https://gist.github.com/) instead?

**Comment by ImPat** [comment]
I'm experiencing the same issue. Android 7.0 ARM64. This only happens if you allow Usage Reporting. The error will disappear after pressing deny. I can't provide logs because I don't have a device to set up right now. Just had this happen to me yesterday and on every device I setup recently.

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius It looks like the field `options.urVersionMax` was removed from /rest/system/config (probably in v0.14.42). I'm pretty sure that wasn't mentioned in any changelog, and anyway you shouldn't make breaking changes in a minor version.

**Comment by imsodin** [comment]
`urVersionMax` never was part of the config, it only lives in 'rest/system/status` (which is unchanged) and the web UI. `URAccepted` and `URSeen` are the values saved in config, `urVersionMax` is just the maximum available version of usage reporting (as in given by the build). These were introduced in 0.14.40.

Also current practice is that config changes aren't considered major (otherwise the above would have been major, and I can remember one other recent config change as well).

**Comment by jebeld17** [comment]
Sorry I forgot to get back. I don't always have time to check my email for this sort of stuff.
Anyways, even after the latest updates, Syncthing for Android is still experiencing the same bug on my HTC U11.

See a revised bug report here: https://1drv.ms/u/s!Atsjh-pCpQhZgpRXOqm0NllIv3IuQw

**Comment by Nutomic** [comment]
@jebeld17 I haven't released the fix yet, but will make a new release soon.
