### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [syncthing/syncthing-android#1055]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by lokesh-krishna** [comment]
I'm willing to give this a shot. Is it okay if the background is a solid color instead of a gradient?

**Comment by c-e-p-x-u-o** [comment]
I'd prefer the solid one.

**Comment by lokesh-krishna** [comment]
So I tried my hand at this and this is what the icon looks like, with various masks:  

![screenshot_2018-05-21 adapticon](https://user-images.githubusercontent.com/20235646/40289402-bbabb58a-5cd5-11e8-834b-fad642a237fa.png)
![screenshot_2018-05-21 adapticon 1](https://user-images.githubusercontent.com/20235646/40289403-bbeafcea-5cd5-11e8-8cc5-7e69aed3c3c5.png)
![screenshot_2018-05-21 adapticon 2](https://user-images.githubusercontent.com/20235646/40289404-bc26f736-5cd5-11e8-9719-af48a6b86c43.png)
![screenshot_2018-05-21 adapticon 3](https://user-images.githubusercontent.com/20235646/40289405-bc628d3c-5cd5-11e8-8ea7-d5b994f4e9a4.png)

I would like to make a PR if the team is okay with this. However the app is presently storing its launcher icons in drawable folders and the [documentation](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) I am referring to to implement this refers to the icons as being stored in mipmap folders. That also seems to be the [general recommendation](https://stackoverflow.com/questions/28065267/mipmaps-vs-drawable-folders#28065664) when it comes to Android.

Is it okay if I move the launcher icons to respective mipmap folders for implementing this or is the present placement of icons there for a reason?

**Comment by AudriusButkevicius** [comment]
So why can't we use the normal logo and just apply masks on that? This feels like a different logo.

**Comment by lokesh-krishna** [comment]
An adaptive icon requires that the icon be provided in the form of a background layer and a foreground layer. The masking is something the launcher handles.  

I provided the above images just to provide an idea of what the icon would look like under different masks.

To use the normal logo as an adaptive icon, it will need to be separated into a background and foreground layer. I used the SVG provided at `graphics/ic_launcher_full.svg` to create these layers. The foreground is just the cluster design, unmodified. The background took the color from the very bottom of the old logo. I went this route because this design looks more in line with Google's Material Design. To use the old logo as an adaptive icon would simply require that the background layer be created with a gradient.

**Comment by AudriusButkevicius** [comment]
Would it not be better to have a transparent background layer and the current logo as the foreground layer?

**Comment by lokesh-krishna** [comment]
It wouldn't because then there would be no telling this icon apart from what is inevitably going to happen come November, when targeting API 26 is mandatory to push updates to apps. When apps target API 26 but do not provide an adaptive icon, their existing icon is thrown upon a white background. 

You can find more information regarding this deadline here: [
Improving app security and performance on Google Play for years to come](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

This is what it looks like when the current logo is used as the foreground layer with a transparent background layer (which is rendered as white).

![screenshot_2018-05-21 adapticon 4](https://user-images.githubusercontent.com/20235646/40294555-bbc7a34e-5cf3-11e8-8e32-fc544f710999.png)
![screenshot_2018-05-21 adapticon 5](https://user-images.githubusercontent.com/20235646/40294556-bc0e9f1a-5cf3-11e8-81f7-8f3a9b616980.png)
![screenshot_2018-05-21 adapticon 6](https://user-images.githubusercontent.com/20235646/40294557-bc55a7de-5cf3-11e8-8f07-853019c91da8.png)
![screenshot_2018-05-21 adapticon 7](https://user-images.githubusercontent.com/20235646/40294558-bc9dc2d0-5cf3-11e8-8208-6e98075b1881.png)

It is tough to make out the white because of the background here though.

**Comment by calmh** [comment]
I think we already have like read and green spinning variants of this logo out there so the brand cohesiveness battle is moot. You have my blessing to do what you like here.

**Comment by lokesh-krishna** [comment]
Thank you so much @calmh. Could you also please offer your input regarding the location of the launcher icons? They are presently located in `drawable` folders but [Google recommends](http://android-developers.blogspot.co.uk/2014/10/getting-your-apps-ready-for-nexus-6-and.html) the use of `mipmap` folders.  

Do I have permission to move the launcher icons to appropriate `mipmap` folders or should I preserve the directory structure?

**Comment by calmh** [comment]
I have absolutely no idea.

**Comment by lokesh-krishna** [comment]
This is why Google recommends using `mipmap`:  
It’s best practice to place your app icons in mipmap- folders (not the drawable- folders) because they are used at resolutions different from the device’s current density. For example, an xxxhdpi app icon can be used on the launcher for an xxhdpi device.

If you think it is worth it then I am willing to move the launcher icons over, else we can continue with the way things are right now.

**Comment by Nutomic** [comment]
The only reason the icons are in `drawable` now is that `mipmap` did not exist when I started this project. So it is absolutely fine if you move them.

**Comment by Catfriend1** [comment]
@lokesh-krishna On my opinion, the gradient looks a little bit better. But I am okay if it gets a solid background and agree with calmh. Would it be much effort to include the gradient, maybe also later after this PR as an "improvement"?

**Comment by lokesh-krishna** [comment]
@catfriend1, It's just that solid backgrounds are more in line with Material Design.

I'm not a designer and I've never made a gradient before but if it is necessary then I think I can figure it out. And I'm open to doing that sometime down the line if it is required.

**Comment by Catfriend1** [comment]
@lokesh-krishna Just a personal thing, but I don't like some elements getting solid color from Windows 8+ and Android 5+... doesn't matter. I've asked a designer to help, here is what I got mailed for you:
[Gradient.zip](https://github.com/syncthing/syncthing-android/files/2029654/Gradient.zip)

**Comment by lokesh-krishna** [comment]
I'll replace the background layer with this but could you please ask the designer to make a version with a resolution of 432 x 432?

**Comment by Catfriend1** [comment]
@lokesh-krishna Done, see PR :)

**Comment by Catfriend1** [comment]
Closed by https://github.com/syncthing/syncthing-android/pull/1095
