### ISSUE TITLE
Feature request: Add Quit button when running in background

### ISSUE THREAD

**Issue by KeyWeeUsr** [syncthing/syncthing-android#1223]
Currently I see no `Quit` or any other button that actually *terminates* the application, therefore if I want to stop Syncthing and spare some resources + battery on my phone, I'm forced to go to the `Applications` menu (or via shortcut by long press on the notification) and then choose to *force* quit the application from the Android side. That isn't really efficient IMO because:

* Syncthing might have a file/DB/connection open and something could get corrupted
* the app might "lock" itself and not start again properly e.g. if you start `syncthing` binary separately (haven't looked at the source, can't say)
* simply navigating to the `Applications` menu is annoying

ref https://github.com/syncthing/syncthing-android/issues/571

**Comment by Catfriend1** [comment]
A windows service doesn't have a quit button ... When running syncthing as a service you need to switch to app run mode if you want to start / stop on demand.

**Comment by KeyWeeUsr** [comment]
Windows? I'm not quite sure what do you mean by that. Anyway... If I'm able to stop the service from Android, you should also be able to quit if from the application it has been run from by sending e.g. something like `SIGTERM` the Android way (or however you communicate App <-> Service on Android).

The point is that I shouldn't be forced to manually quit the app running in the background with a non-standard approach and somehow cripple my data in the process (argument that I should't be force-killing apps that can't be stopped normally isn't acceptable) which for Syncthing might cause rather annoying results that hopefully would "just" require to either only rescan or even readd all folders.

A real life example: when I have 10% of battery left and I really need the device to run next few hours at least, one of the first things I do is stopping stuff running in the background e.g. navigation, syncs, music, social networks ... While I don't care e.g. about Facebook/Mastodon/etc mangling itself when I stop it, I do care about syncs and music. Music has a nice "X" which to me indicates that the devs took care about properly exiting the service + app. Syncthing does not and that makes me worried.

**Comment by Catfriend1** [comment]
Well the point is by design a service is an always running thing. So I think the word leads to misunderstanding. I see your point, please first try if you get the desired behaviour by ticking the run condition option "respect android's quick toggle auto sync data". You can then make it stop when on low battery by disabling the quick toggle in androids status bar tiles. If thats not enough, I advise to run syncthing on demand - thus disabling the always run in background option. You can then run the app, press home go to another app, if a run condition is met syncing will take place and then, if you'd like to quit you press home, bring the app to front again and hit the quit button from the drawer menu.

**Comment by KeyWeeUsr** [comment]
Ah, I see, the mistake is on my side. Basically the Syncthing on demand is what I was describing. I didn't really try it because I thought once I leave the app Syncthing stops too, so I turned the service on by default.

Now it seams the sticky notification is available anyway with the app syncing in the background and without a service. Looks good to me, thanks!
