### ISSUE TITLE
Other devices are shown as disconnected

### ISSUE THREAD

**Issue by youknow10** [syncthing/syncthing-android#1411]
I've added some devices in the app. It shows them as "Disconnected". In the Web GUI, it shows "i/o timeout". It even shows the correct IP address for the devices. But cannot connect to them.

My laptop (on the same network) has no problems with those devices. It sees them as connected and syncs with them with no issues. The only problem is with the app.

### Version Information
    App Version: 1.2.2.4
    Syncthing Version: v1.2.2
    Android Version: Android 8.1 / LineAgeOS 15.1
    Device manufacturer: Samsung
    Device model: GT-I9195

**Comment by AudriusButkevicius** [comment]
Hey,


As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
