### ISSUE TITLE
[Feature Request] New condition: hotspot enabled

### ISSUE THREAD

**Issue by jdorel** [syncthing/syncthing-android#1439]
# Start syncthing when hotspot is enabled

Would it be possible to start syncthing when hotspot is enabled ?

There would be two different situations:
  * mobile data is disabled
  * mobile data is enabled

## Mobile data is DISABLED

There is no restrictions (compared to when it's enabled)

The typical use case would be to sync files between a phone and a computer without having to plug in a cable, and when no WIFI network is available.

## Mobile data ENABLED

If you don't want syncthing to use your mobile data, syncthing could restrict syncing to the hotspot interface.

The typical use case is when you are using your phone to provide internet access to your computer, and you still want syncing to work.

The computer should also not try to sync with devices beyond your phone (through filtering or through device notification).

**Comment by jdorel** [comment]
The solution in #1238 would work for the first case, but not for the second

**Comment by AudriusButkevicius** [comment]
Second case is not possible, as there is no notion of different interfaces in android I believe. You are either connected to the internet or not, you cannot be connected only to the hotspot.

**Comment by AudriusButkevicius** [comment]
As in, the application has no say in routing rules.

**Comment by AudriusButkevicius** [comment]
Based on that, closing.

**Comment by codethief** [comment]
> The solution in #1238 would work for the first case, but not for the second

@jdorel Am I understanding this correctly that even when I have mobile data *enabled* on my phone (as well as the hotspot feature), Syncthing still doesn't fire up because Android doesn't report the hotspot as a wifi network that's connected to the internet (although it kind of is but obviously it's the phone's mobile data connection that connects this wifi to the internet), so therefore Syncthing thinks only mobile data connections are available?

**Comment by jdorel** [comment]
Yes
