### ISSUE TITLE
CRITICAL BUG - sharing folders can not be undone 

### ISSUE THREAD

**Issue by ecxod** [syncthing/syncthing-android#1464]
SYNCTHING VERSION : 1.3.3
SYNCTHING ANDROID VERSION : 1.3.3

**DESCRIPTION:**
If you happen to share a folder by failure with somebody, and then you undo the sharing, it will not be undone.  It continues.

**WHAT SHOULD HAPPEN:**
What should happen is to not share IMMEDIATELY any more bit and delete the files on the other side immediately.

**WHAT REALLY HAPPENS:**
The sharing will silently continue after you undo the sharing and you give the whole content of the folder. 

**OCCURRENCE:**
The bug happens only on Android version as far as I have noticed. I have noticed this bug between a Android sender and a Windows receiver. I was not able to undo the folder, 
The other part had to accept the folder because it continued to appear in the top of the screen the notice that android wanted to share a folder.
When I looked at the Android device the sharing had checked itself again from alone. 
So I unchecked again, but with no repercussion. 
Windows continued to receive the notice that Android wanted to share the folder.
So in the End Windows ignored the message.
Then I unchecked The folder and we supposed everything was fine. So I told the Windows that he can delete the ignore from The Menu, and in the moment when he deleted the ignore, I got the check in the folder again and Windows got the message that I want to share the folder.

**Comment by AudriusButkevicius** [comment]
You probably have introducer or some other advanced option enabled. You can also try unsharing it from the web ui.

**Comment by ecxod** [comment]
This is the critical aspect, that it is unchecked in the android ui, but in the web ui it reappears checked as soon as you close the web ui from alone.
Then I uncheck it again in the web ui and clode the web ui and it appears checked in the android ui.
And you can continue forever like this.
Listen, whoever you are, this is very critical. If I uncheck it must stay unchecked. AND DELETE what has beed transited . No comment.

**Comment by imsodin** [comment]
> No comment.

Bugs with the reporter not commenting on questions asked by maintainers are not fixable -> closed.

If you decide to comment, please do so on https://forum.syncthing.net/. Once we found out what's wrong and it is a bug, we can open a proper issue.

**Comment by ecxod** [comment]
I have described the bug very exactly. And Mr Audriutus made a instant "fast-shot" and I answered him that the android ui and the web-ui are not working together.
Wat do you want me to comment ?

**Comment by Catfriend1** [comment]
Well, in my eyes, users should not use the web ui because the wrapper may be uninformed about the config changes in some "race like" conditions. That's because the wrapper holds the config cached in memory, too and writes it back when it's required. Making changes simultaneously on both UI's - native and wrapper - has already led myself into the described problem regarding other options. I did commit some cure to counter this problem back in 2018 with my PR's but it can't be solved 100%. The more is change-able from the wrapper, the more conflict could probably arise in race conditions between both config instances. It is not a bug in Syncthing, though. We could discuss on the forum how to solve it properly.

**Comment by imsodin** [comment]
Please continue at https://forum.syncthing.net/t/problem-un-sharing-folder-on-android/14352 (thanks for moving this discussion to the forum as requested!)
