### ISSUE TITLE
Syncthing disabled on VPN

### ISSUE THREAD

**Issue by shawn1thompson** [syncthing/syncthing-android#1496]
I'm using ProtonVPN and have enabled split tunnelling to allow Syncthing to connect to the LAN, but it remains disabled.

### Version Information

    App Version: 1.4.2
    Syncthing Version: not displayed in app
    Android Version: Android 9

Log attached
![Screenshot_20200426-165635](https://user-images.githubusercontent.com/32218754/80320992-6169c580-87df-11ea-936a-2a712323baff.png)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
