### ISSUE TITLE
Symlinks lead to "out of sync"

### ISSUE THREAD

**Issue by adnion** [syncthing/syncthing-android#1537]
This https://github.com/syncthing/syncthing-android/issues/1203#issuecomment-408683873
suggests:
```As a workaround you can add (all...) symlinks to ignored files.```
This is manual work for every android device you use.

According to https://github.com/syncthing/syncthing/issues/92#issuecomment-53230568
the option to ignore symlinks was removed
```Because it's dangerous and messy, and was only a workaround for not having multiple repositories.```

Please make syncthing's android version smarter with regards to symlinks.
Thank you!

**Comment by AudriusButkevicius** [comment]
A lot of time has passed since then. Symlinks are now handled by syncthing (syncthing-android just adds a ui on top of syncthing so uses the same code) so if you are seeing issues, it's most likely not related to the fact its a symlink but due to permissions or medium it's on (not sure if exFAT supports symlinks). 

If you want to further discuss this, open a thread on the forum with the error messages.
