### ISSUE TITLE
Unable to change folder type on SD card

### ISSUE THREAD

**Issue by serpro69** [syncthing/syncthing-android#1554]
Giving access to SD card does not seem to have any effect and folder type still can't be changed from "Send only".

Android 10
Syncthing 1.9.0

Let me know what other information I can provide.

**Comment by AudriusButkevicius** [comment]
Write access in SD cards is not supported, I think the FAQ and the wiki covers that.
The only way around is root access,

**Comment by Aare07** [comment]
Yes Wiki and FAQ are clear.
But:
In the two years since the new behaviour of Android with SD Cards is in place, almost all applications managed the change and use SD Cards now.
Please take the work and change the wraper and sincthing to support SD Cards as the user expects: Just ask permission once uand write anywhere on the SD Card filesystem the user likes
 It's my dream :)
 Thank you
