### ISSUE TITLE
App using camera forever after scanning device ID

### ISSUE THREAD

**Issue by ph-legacy** [syncthing/syncthing-android#1614]
**Steps to reproduce**
- Add device by scanning QR code
- Let app sync data
- Close app

**Current behavior**: App continues to use camera

![syncthingcsmera.png.png](https://user-images.githubusercontent.com/383295/109629393-0eba1200-7b44-11eb-9122-3d4f896845f1.png)

![Screenshot_20210302-103857_Permission_controller_1.png](https://user-images.githubusercontent.com/383295/109629262-f1854380-7b43-11eb-970f-1384c87a39de.png)

**Expected behavior**: App turn off camera after the device ID was scanned

### Version Information

- App Version: `1.13.0` (F-Droid)
- Syncthing Version: `1.31`
- Android Version: Android 10, LineageOS (degoogled) `17.1`

**Comment by imsodin** [comment]
PR introducing that functionality: https://github.com/syncthing/syncthing-android/pull/1556

@sumit-anantwar Could you have a look please.

**Comment by FaceToKeyboard** [comment]
I can reproduce by using the Add Device interface, tap the QR code icon to bring up the camera, then go 'back' to the previous screen. Camera remains in use.

If I instead tap 'Cancel' in the camera/scan mode - instead of going 'back' - the camera does properly stop being used.

I discovered this issue after noticing a massive battery drain.
