### ISSUE TITLE
Feature request: Run on a timer (wake up and sync every X minutes for better battery life)

### ISSUE THREAD

**Issue by arrrlaska** [syncthing/syncthing-android#1729]
Sorry if this is a repeat, I couldn't find any similar issues/requests out there.

Simply put, I'd love an option to allow syncthing to wake, sync fully (or at least run for Y minutes), then sleep for X minutes while on battery, in order to preserve battery life.

Much thanks! Loving the app!!

### Version Information

    App Version: 1.18.3
    Syncthing Version: v1.18.3
    Android Version: CalyxOS 2.11.0

**Comment by imsodin** [comment]
There's e.g. tasker or easer for this kind of thing. For the app itself it is out of scope - both because catering all kind of use-cases like this might clutter the app, and because no-one is actively working on it. And [catfriends1 syncthing app](https://github.com/catfriend1/syncthing-android) might even already have something like this.
