### ISSUE TITLE
Accessing folders and files from synced devices

### ISSUE THREAD

**Issue by gg-gg1** [syncthing/syncthing-android#1894]
Hi! First, I want to thank you for this amazing service and all the hard work of all contributors of the project. 
I would like to suggest the implementation of accessing files from other synced devices. For example from Syncthing on Android, I would like to access the files from my pc which runs SyncTrazor. This would be a very good replacement of a cloud and all the headache of setting up a NAS and so on.

Thanks!

**Comment by contrapunctus-1** [comment]
@gg-gg1 This sounds similar to the Syncthing-Lite project, whose stated aim was to view the files on other Syncthing nodes, and selectively download them rather than maintaining clones of the directories on each node. AFAIK it is not being developed, but it's technically possible for Somebody (TM) to resume its development.

**Comment by imsodin** [comment]
yeah what @contrapunctus-1 said, abd this is out of scope for this app.
