### ISSUE TITLE
Latest update makes headers nearly unreadable when using dark mode

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing-android#1915]
Please see the top of this screenshot:
![Screenshot_20230613-012529297](https://github.com/syncthing/syncthing-android/assets/47056543/6aa559b6-3050-4549-be16-1b557165e720)

Previously, the header text was not white-on-light. (EDITED.)

### Version Information

    App Version: 1.23.5
    Syncthing Version: 1.23.5
    Android Version: Android 13

**Comment by imsodin** [comment]
This is most likely an effect of https://github.com/syncthing/syncthing-android/pull/1895 - @Bnyro, could you take a look at this please.

**Comment by Bnyro** [comment]
It should be fixable by modifying or removing the two following lines:
https://github.com/syncthing/syncthing-android/blob/7b669e77ddbd2879c46a4f8a0ed80dbe60b2b889/app/src/main/res/layout/widget_toolbar.xml#L9

https://github.com/syncthing/syncthing-android/blob/7b669e77ddbd2879c46a4f8a0ed80dbe60b2b889/app/src/main/res/layout/activity_main.xml#L19

We can either use `colorSecondary` or remove the lines, so that a variant of the background color is used automatically (second might be the best).

Then we also need to modify the status bar color:
https://github.com/syncthing/syncthing-android/blob/7b669e77ddbd2879c46a4f8a0ed80dbe60b2b889/app/src/main/res/layout/activity_main.xml#L19
It should either fit the other color we picked for the toolbar (e.g. `colorSecondary`) or we could use `@android:color/transparent` for the second option.

I'm currently a bit too busy and lazy for setting up the development environment again, it would be great if you could do these changes for me @imsodin, since you probably already have things set up (I recently switched the distro).
