### ISSUE TITLE
Waiting for api

### ISSUE THREAD

**Issue by vedranf** [syncthing/syncthing-android#196]
Hello,

Unfortunately I don't have many details, but as soon as I configure a directory and add few devices I get  endless "waiting for api" popup. Restarting phone or reinstalling syncthing doesn't help. Phone is Samsung S4 mini with android 4.4.2 reset to factory defaults. I didn't see anything relevant in logs.

Thanks,
Vedran

**Comment by jibe-b** [comment]
Hi, I get the same on a samsung galaxy note 10.1 2014 edition (SM-P600). Android has version4.4.2.
Syncthing keeps spinning indicating En attenqe de l'API, i.e. waiting for api in French.

Best regards

**Comment by exitcode1** [comment]
On a galaxy note II running 4.1.1 and syncthing 0.5.12. I'm new to adb/logcat and couldn't figure out what incantation would give me what is needed. I can run whatever requested if you hold my hand and use little words, heh. Perusing it on my own I saw errors and warnings pouring out of a couple different things. I rebooted, ran syncthing, and ran this command:
`adb logcat PollWebGuiAvailableTask:V SyncthingService:V PostTask:V *:S > syncthingandroid.log`
which yielded this (hopefully related?) [output](http://pastebin.com/hVHpgFma).

**Comment by Nutomic** [comment]
Does the syncthing UI show when you open `127.0.0.1:8080` in the browser on your phone?

**Comment by vedranf** [comment]
Yes, it does. Except saying "creating symlink: operation not permitted" for 2 symlinks, it appears to be working as expected from browser.

**Comment by vedranf** [comment]
Ah, I've just read what exitcode1 pasted. I guess it's due to some Samsung protection (knox?).?

**Comment by Nutomic** [comment]
I really don't see why there could be a problem. Syncthing is running with the right port, and the app is properly polling on the same port.

Did you let the app run for at least a few minutes? Maybe there is something else in the log?

**Comment by svrnwnsch** [comment]
I am having the same Problem on a Fairphone 1.
My guess is that the error is caused by setting the webinterface to https via the webinterface. Maybe the App tries to connect without https to the client and fails into a loop without any timeout?

**Comment by svrnwnsch** [comment]
This worked for me:
1. Connect via webinterface `https://127.0.0.1:8080` 
2. Go to settings and disable https for webinterface
3. Restart Syncthing via the Webinterface
4. Force Syncthing app to stop via Android Settings
5. Start Syncthing app, which should no work.

**Comment by Nutomic** [comment]
Ah, that would be #19. 

The problem is that the web GUI uses a self-signed certificate, and we'd need to do cert pinning for Android to accept that. But the certificate is in a different format than what Android wants, and I didn't manage to convert it.

**Comment by exitcode1** [comment]
Not a dupe; same "Waiting for API" symptom with HTTPS off.

**Comment by svrnwnsch** [comment]
can you acess http://127.0.0.1:8080 or does this redirect you to https?

**Comment by exitcode1** [comment]
In my case, http loads and populates fine. Syncing itself and https still work (after getting past the cert warning). App still only ever says Waiting for API.

**Comment by Nutomic** [comment]
@exitcode1: Do you properly restart the app after changing the HTTPS setting? Maybe try to restart the device?

Anyway, I can't do anything without a log.

**Comment by rdiaz02** [comment]
I am having the exact same problem: I get the eternal "Waiting for API" whenever I make any changes to folders. No, I am not using HTTPS.

**Comment by Zillode** [comment]
@rdiaz02 we are in the process of fixing this, I know where it goes wrong

**Comment by StefanCodes** [comment]
I ran into this as well and the problem was Adblock Plus. When I got to my home wifi (when the Adblock Plus proxy settings kick in), Syncthing started hanging on the Waiting for API dialog. I let it sit there for more than 20 minutes twice, restarting the phone between tests. Disabling the proxy for my wifi connection in Settings and restarting Syncthing fixed the problem immediately.

This isn't Syncthing's fault, I don't think, but if other people can reproduce this it might be good to put on the FAQ.

**Comment by Nutomic** [comment]
I think you can edit the wiki yourself, would you mind to write it down? :)

**Comment by StefanCodes** [comment]
Created https://github.com/syncthing/syncthing-android/wiki/Troubleshooting.

I don't do Android dev but I'm good at documentation - let me know if you need help anywhere else on the project!

**Comment by rdiaz02** [comment]
I do not know why this (and #279 ) is being closed. I am still experiencing this problem, and I do not have Adblock Plus. In fact, the problem appears consistently in two different android devices. For instance:

- If I change a configuration setting, when I click on restart, it will hang on "Waiting for API" forever.

- If a device goes to sleep, when it wakes up, the ST Android UI will hang on the "Waiting for API" forever.

The way I deal with this is to let it start, then kill the app, then restart a second time. Oh, and I avoid changing settings (sync interval, devices, etc) from the Android UI, since this often will lead to a restart that never completes, and then the setting does not stick. I only do it from the Web GUI, which (if the underlying android app is running) is a lot more consistent in behavior.

**Comment by Nutomic** [comment]
Great, thanks :+1: 

I don't know anything we need in particular, but feel free to write down anything you deem useful (maybe a general faq).

Also, don't hesitate to ask if you need any clarifications ;)

**Comment by rdiaz02** [comment]
I am not sure this is really completely fixed. I still get the long (over hours) "Waiting for API" in devices that go to sleep and wake up. It is random, and I can not always trigger it.

**Comment by Sendery** [comment]
I did fix this "temporaly" by turning on the Wif and then off when the "api is enable"/loadedi. I think the 3g/LTE/HSPA or whatever you have dont work on startup.
