### ISSUE TITLE
Device shows 99% done

### ISSUE THREAD

**Issue by Bouni** [syncthing/syncthing-android#197]
My Nexus 4 shows Synchronisiere (99%) from the start of the sync process which is not correct. The webgui of the target shows the correct percentage.

**Comment by lsascha** [comment]
same issue here since i switched to the Version supporting syncthing 0.11.
Since the android webgui does not show any percentages or anything i am not 100% sure but it looks like it is actually synced completely since it does no longer upload or download anything and it shows all 25 files i sync and the same size as the other devices and it shows "Up to Date" there.
So i guess it is just a display error on android.

Running Android 5.0.2 Stock on Sony Xperia Z2.
![screenshot_2015-05-08-11-55-40](https://cloud.githubusercontent.com/assets/4083570/7534320/dc567368-f579-11e4-9ca1-ec25e6e21f84.jpg)
