### ISSUE TITLE
Can't change number of connection above 1. 

### ISSUE THREAD

**Issue by maikelthedev** [syncthing/syncthing-android#1992]
Syncthing Version: v1.23.7, android (64-bit ARM)

I can't change the number of connections to anything on the Android app. On the PC I can set it up to anything but still when connecting to the phone it still says 1. In the menu I can change that (on the PC) but not on the android app. Since I'm sharing folders with hundreds of tiny files, it takes ages to sync when only 1 file is synced at a time. 

Is there a way to change this or is it something that simply is NOT implemented yet on this version?

I mean if it is a wrapper, why not update the underlying syncthing to the latest and greatest so I can change that on the GUI.

**Comment by er-pa** [comment]
Multiple connections was added to 1.25.0 (and its release candidates). But, using multiple connections is not gonna make a big difference when it comes to handling many files on Android, that's known to be slow due to the used file system and/or Android framework.

Multiple connections is actually more or less a niche thing, mostly useful when the used connections are limited for one reason or the other (e.g. QoS-rules). A single connection, in most cases, has a limiting factor far beyond the limiting factor of the file system.

**Comment by maikelthedev** [comment]
> Multiple connections was added to 1.25.0 (and its release candidates).

In any case can we have the version shipped with the Android app from 1.23.7 to 1.25 or above?

**Comment by tomasz1986** [comment]
> Since I'm sharing folders with hundreds of tiny files, it takes ages to sync when only 1 file is synced at a time.

Multiple connections won't help you with this one. The problem is due to how newer versions of Android allow applications to access files. For example, I personally run Syncthing on multiple Android devices - on Android 7, synchronising 10,000 tiny files takes 15 minutes or so, while on Android 11, it takes at least a few hours.

**Comment by maikelthedev** [comment]
Oh no I'm on Android 13, which might explain why it has taken 1 month. 😱

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
