### ISSUE TITLE
Directory selection: button navigate "up the tree"

### ISSUE THREAD

**Issue by Cathryne** [syncthing/syncthing-android#200]
maybe related to #29

I'm running Syncthing on a Jolla phone with [Sailfish 1.1.1.27](https://together.jolla.com/question/71741/release-notes-software-version-11127-vaarainjarvi/) and Android-app support. That means the directory selection in Syncthing starts in `/home/nemo/android_storage`.

Unfortunately, the photo directory is above that, but Syncthing doesn't provide a way to to navigate up the directory tree. AntennaPod for example does ([1](https://github.com/danieloeh/AntennaPod/blob/9659c18d899349d9be1573fb9520defc7d3a19cd/app/src/main/AndroidManifest.xml#L197), [2](https://github.com/danieloeh/AntennaPod/blob/563ceaf39332943b1733036f5c3b9087c481d313/app/src/main/res/xml/preferences.xml#L139)).

If you would implement this, I think it would be(come) the 1st photo syncing solution for the Jolla ;-) Assuming it would be allowed to read folders outside `/android_storage`.

**Comment by Nutomic** [comment]
I assume that directory is what Android apps are given as "sd card"?

This is a bit weird, since going up should return you to the list of root directories. And on Android, these should contain all directories that can be accessed by the user. 

So I neither see a good way to do this in the UI, nor do I think this is a good feature at all (it would be confusing for Android users to move into system root).

Maybe you could change the "sd card" path for Android apps somehow? Or is there some API to determine that we are on Sailfish?

**Comment by Cathryne** [comment]
Oh, thanks for the suggestions. It did let me select the folder, but after restarting "Permission denied" is displayed for that folders `/.stfolder` :-/ Not your problem, though, I'll notify Jolla about this.
