### ISSUE TITLE
i18n: Pull in Weblate changes

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing-android#2088]
Just a heads up @imsodin, there was an warning on Weblate stating that the Weblate repo had diverged significantly from upstream.  I tried to mitigate it by rebasing the Weblate changes onto current `main`, but those are now 25 unmerged translation commits.  So it seems in fact there was no merge for some time.

Please consider merging https://github.com/syncthing/syncthing-android/tree/weblate again soon-ish.  Should do that regularly to avoid such warnings.

**Comment by imsodin** [comment]
I generally do that before releases, which is enough (hopefully). Right now due to my travels that was a few months though (and that *** google play situation doesn't seem to resolve...).

I am slightly confused on two counts though:



> I tried to mitigate it by rebasing the Weblate changes onto current `main`

I thought rebasing isn't good, because weblate gets confused if it's branch gets moved (instead of just appended to). That's why I did merge commits so far.



> Please consider merging https://github.com/syncthing/syncthing-android/tree/weblate again soon-ish.

Looks like the branch is rebased on top of current main, so nothing to merge at the moment? Did you just intend to let me know to do it again in less than three months this time? :)
