### ISSUE TITLE
[Feature] add restart button to native GUI

### ISSUE THREAD

**Issue by urza** [syncthing/syncthing-android#257]
When changing settings and adding new devices/repos it asks whether to restart syncthing now or later. However I didnt find any button in native GUI to restart syncthing.

**Comment by Nutomic** [comment]
That's what the dialog is for. And if you choose "restart later", there's a notification to restart.

I don't think a restart button is really needed.

**Comment by Zillode** [comment]
I agree with @Nutomic, a restart button would clutter the GUI and we should keep this simple.

**Comment by Dinduks** [comment]
I stumbled upon this issue after looking up *syncthing android restart* on a search engine. 
I didn't get a dialog box, and I didn't notice the notification. The notification area is anyway not the right place for this kind of message (it should be obvious to the user).

@Zillode, whether the button would clutter the GUI or not, is a matter of where it would be placed.
But the usefulness of such a button (it doesn't have to be a *button*) is not debatable UX-wise: 
* What happens if I say *no* to the restart dialog by mistake, and wanna restart manually?
* What happens if I wanna restart the application while debugging a problem (which is my case right now)?

Should I manually kill the application? Not only is this bad UX, but killing the app might make it unstable, break the database, or leave a PID file open e.g.

An obvious place to put such a button is the menu, where *Donate*, *Settings* and other buttons are.

I call you to reconsider your decision.

Thank you.

**Comment by Nutomic** [comment]
Wow I actually don't even remember this issue.

Anyway, there's a new issue for the same enhancement (#420), and I think it absolutely makes sense and should be added.
