### ISSUE TITLE
clicking "add new device" or one existing device crash the app

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#266]
Hi,
at 100% reproducibility if i click "add new device"  or on one existing device on the device tab the app crash. i can't even send a report (i think i installed it with f-droid, but if can be more useful i'll install it on play).

synchronization with the device (A) seems to work, but adding the phone's id  (P) to another device (B) does not pop up anything in the M's apps; adding A to B does pop up a sync request on the B machine, so everything is running (the device are all in the same home wlan, so no firewall between them)

Now that im doing some more check, syncornization between A and M say it is at 30% on M, and at 7% on A, and it does not seems to change.

**Comment by Zillode** [comment]
Fixed in https://github.com/syncthing/syncthing-android/commit/2b9a79bdada5b8bce2d310cc145fe17122d97e63
Will be in F-Droid tomorrow and Play store within a few hours.

For the synchronisation itself, I suggest you provide a [logcat](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports)
