### ISSUE TITLE
Forever "Waiting for API"

### ISSUE THREAD

**Issue by urza** [syncthing/syncthing-android#279]
I just opened syncthing app on my android after updating it today. It is in "Waiting for API" forever. Pressing back button does not help.

**Comment by v6ak** [comment]
Do you have configured the password? If so, see #261.

**Comment by urza** [comment]
No password.

I tried to shut the syncthing app down from android app manager. It didn't help.

Restarting the phone helped.

**Comment by Nutomic** [comment]
Logcat would be helpful in case you (or anyone else) gets this again. Otherwise, we can just guess.

**Comment by yair** [comment]
I can replicate this issue reliably by editing a folder option (e.g. changing the rescan interval) and asking for a restart. I think it also happens when I dis- and re-connect to WiFi.
I think the problem is that the older instance isn't 'completely dead' when the new one is launched, making the new one crash on init --

03-25 20:34:55.575 I/SyncthingNativeCode(6054): [O4R54] 18:34:55 INFO: syncthing v0.10.29 (go1.4.2 linux-arm android) unknown-user@android.syncthing.net 2015-03-22 14:09:14 UTC
03-25 20:34:55.577 I/SyncthingNativeCode(6054): [O4R54] 18:34:55 INFO: My ID: XXXXXX
03-25 20:34:55.597 I/SyncthingNativeCode(6054): [O4R54] 18:34:55 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?
03-25 20:34:55.599 E/SyncthingNativeCode(6054): Syncthing binary crashed with error code 1

Waiting a bit and restarting the front end works as a workaround.

**Comment by Zillode** [comment]
@yair can you provide a few additional lines that happened before this message?

**Comment by yair** [comment]
@Zillode Sure, here is the log since I entered the main window (from running in the background) - http://pastebin.com/UnbaJ69B .

**Comment by Nutomic** [comment]
I don't see anything unusual in the log. If this is reproducible, can you try if `localhost:8080` is reachable in the browser before/after you open it?

**Comment by Zillode** [comment]
@yair : I still need more data, I think something went wrong in the background which makes that syncthing is still running (because the db is locked). Can you further extend the logcat?
Thanks

**Comment by yair** [comment]
@Zillode : You can find a full log from launch to crash here - http://pastebin.com/Vkw1ftB0
@Nutomic : localhost:8080 is reachable until the crash, but not after.
Other things that might be related (or might merit a new ticket):
- CPU usage is always above 25% while ST is running (probably a thread stuck in a busy loop).
- Devices are reported by the app to be disconnected even after the log (and the remote ST instances) indicate they are connected and synced.
Are there any relevant 'Debug Options' I can give that might help debug this?

**Comment by Zillode** [comment]
https://github.com/syncthing/syncthing-android/issues/196 by https://github.com/syncthing/syncthing-android/commit/65e090f6e95b8426d914f4160cd351e2d48d52d1
