### ISSUE TITLE
no new installation possible

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#290]
I cannot load the configure file.
Web interface is not available.
Crashes after add new device.
Wrong syncthing release.
Was this release made public completely untested?

**Comment by Zillode** [comment]
Please provide a logcat. I just verified the Play apk and I can add devices and see the webinterface.
The wrong syncthing version was a problem with our new deployment strategy via Jenkins and has been fixed in its configuration.
The only thing that I see is broken is https://github.com/syncthing/syncthing-android/issues/289, i.e. not showing the dialog on startup.

**Comment by Nutomic** [comment]
Cmon Github, I closed this :p
