### ISSUE TITLE
Global discovery defaults to on

### ISSUE THREAD

**Issue by gdt** [syncthing/syncthing-android#373]
When starting syncthing-android (0.5.28, 0.10.30, from f-droid), global discovery defaults to on.  This seems like a privacy leak, albeit minor.   So I would suggest defaulting to off.    local discovery is arguably less of an issue.

**Comment by AudriusButkevicius** [comment]
I don't think it's right, as half of the people will not even understand why syncthing doesn't work.
It defaults to on on the desktop client, hence it should follow the trend.

If you care enough aboutprivacy, I guess you'd read the howtos/guides etc to understand how syncthing can provide that to you, rather than blindly trusting it.

**Comment by wbedard** [comment]
While I also agree that the privacy leak is minor, as something of a privacy advocate myself, I would also prefer that the default be to protect the user.  A simple workaround would be, during Syncthing's initial run, to present a simple "wizard screen" that explains the local/global discovery options and both informs the user and allows them to select their preference.  Should a setting not be selected, this screen should be displayed upon subsequent starts of the application.  Many Android applications use this wizard approach to assist the users in initial configuration.  For that matter, Android itself operates this way during initial startup of a new device.

**Comment by AudriusButkevicius** [comment]
True, if you are willing to invest your time to implement this, I agree this could be an option.

Given the current climate of the app, and constantly having to play catch up game due to syncthing itself changing rapidly, I feel there are bigger problems to solve.

**Comment by calmh** [comment]
(Not even an android user here, just an opinion.) Defaulting to on is the only sane choice from a developer point of view, lest we spend the rest of our lives explaining and closing `Syncthing does not connect`-issues here. This also matches the behavior of syncthing "core". There is a document on syncthing that explains the various data leakage that happens when run in it. 

To summarize, a wizard of some kind (in the android app, and the regular web GUI) would certainly be nice. Until then, I think it's the right choice to default to the simplest usage, and let the *extra* privacy conscious do the research?

**Comment by gdt** [comment]
The privacy leak seems pretty serious, on thinking about it.   It reports a unique id for a device and an IP address to a  server not run by the user, and it does this persistently, unless I'm misunderstanding it.   I'm not saying the introducer admins are evil, but after deanonymizing the ID, the server has access to real-time IP-based tracking.   I get the point though that the issue is best raised with the main client.

**Comment by Nutomic** [comment]
I see where you are coming from, but this is definitely a wontfix in my opinion.

As said by @AudriusButkevicius and @calmh, this would make the app unusable to new users, and would flood us with bug reports. I also don't want to make a wizard, because it adds extra friction.

Think about it this way: Dropbox doesn't ask you if it may connect to a server, and that's the level of simplicity we need for broad adoption. If you care about it that much, disable the setting, or make a "paranoid" fork if you want.

(leaving this open for further discussion)

**Comment by gdt** [comment]
Thanks for the discussion; I understand that the tension between privacy and usability is difficult.   I wonder if making global discoverability highly obvious on the main screen, with a toggle "sync on local net only"  vs "report location to global rendezvous server", might help.

With global discovery as a default, the privacy bullet under https://syncthing.net/ needs updating; it says there is no centralized server that might be compromised.  That's true for data exchange, but not for tracking a user's location.

**Comment by calmh** [comment]
I think that caveat goes for most things in the world. Probably every device you own tracks your "location" (as in mapping some identifier to your IP) when doing update checks (think Android, iOS push notifications, Windows update, browser update checks every time you start it, and so on). And note that syncthing is all about *data privacy* not about hiding that you use it, or providing anonymity. The summary on https://github.com/syncthing/syncthing/wiki/Information-Leakage captures this - "the actual transmitted data is protected as well as we can".

**Comment by calmh** [comment]
Also, just for the record, the discovery server does not keep history. So compromising it can give you access to the current device ID <-> IP mapping, but not historical or future information (unless the compromise goes unnoticed for a long time).

**Comment by lfam** [comment]
calmh, please correct me if I'm wrong, but I think the stance of the syncthing project has always been that the syncthing app is a reference implementation of the block exchange protocol. The hope is that others will make other clients using the protocol. There's nothing stopping anyone from forking or starting fresh and using a more secure method of peer discovery.

Plus, the discovery server software is also available so you can run your own discovery server.

Syncthing as a protocol will probably never take off if the reference app doesn't sync by default, which is what is suggested by this bug report.
