### ISSUE TITLE
Showing same status info for all devices in device list, 0.7.0-beta2

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-android#473]
Testing latest beta, my device list shows same status for all devices in device list, so if first connects, it shows syncing (xy%) for all, then "Up to date" for all etc even for devices that are not connected (because they are not even running). I could get some log, if you want (but log feature is also broken, #470 )

**Comment by Nutomic** [comment]
Right, I can reproduce that.

@calmh @AudriusButkevicius I assume this is due to a change in `/rest/system/connections`. [According to the documentation](https://github.com/syncthing/docs/commit/8c76d69c467e4af0ebba646efa5a3e09d11ec63b), there's some additional data added, but nothing that would cause a problem (and I'm not getting parsing errors either). Any idea what causes this?

**Comment by AudriusButkevicius** [comment]
So I wonder if its a bug on our side?
Can you actually get the rest call output as it happens?
