### ISSUE TITLE
Easier debugging, now that it's possible from the backend

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-android#504]
Since Syncthing 0.12, you can get a [list of debug facilities](http://docs.syncthing.net/rest/system-debug-get.html), present checkboxes for each of them, and push the results to [the same endpoint](http://docs.syncthing.net/rest/system-debug-post.html). The [log](http://docs.syncthing.net/rest/system-log-get.html) can also be polled every few seconds and be presented. Or we could just access the log on disk, probably (unless it's broken?). It would be neat if this was available as an easier option than setting STTRACE and restarting and stuff.

**Comment by Catfriend1** [comment]
Hi @calmh 
after over 2 years we've merged a PR to improve the debugging options UI of the android wrapper. Querying the REST API and enabling/disabling STTRACE options at runtime  was declared as hard and "error prone" to implement in PR #1109  discussion by @Nutomic . So I've made a PR to do this via the environment variable including a nice UI showing available options on the UI with check boxes. As this hardcoded list could go out of date (see @AudriusButkevicius comments) a new PR #1114 is on the way that reads the list of available facilities from the REST API once on first binary launch or binary update and caches it. This is a compromise I found best fitting for the current situation the app's code doesn't fit all basic needs to do this all live plus the reason syncthing doesn't even start on some special android platforms.
I think we can close this after it got merged or do you still being after the complete REST API implementation instead of the environment variable in use?

**Comment by calmh** [comment]
This (three years old) issue came about from frustration about error reports from Android users, with said users never being able to provide useful log output. I don't particularly care at all about the implementation, as long as the end result is that it's possible to figure out what's going on when a problem happens. :)
