### ISSUE TITLE
Syncthing disabled if no internet

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#540]
If no internet is available I get the `Syncthing disabled EXIT/CHANGE PREFS` dialogue.

So I can exit or see the preferences activity where back arrow exits the app.

I can't add/remove/change folders/computers or interact with WebGUI if no internet is available.

Starts working ok once I turn Wi-Fi on though.

**Comment by licaon-kter** [comment]
@capi 

Tested:
* have ''sync on Wi-Fi off" -> no error
* have ''sync on Wi-Fi on" w/ *no connection* -> "Restrict to certain..." does not even open
* have ''sync on Wi-Fi on" w/ "Restrict to certain..." with *one*, *two* or *no selected network* -> error occurs

BTW, with the dialogue open and enabling Wi-Fi, the dialogue disappears and the app continues correctly.
Enabling mobile data though does not let the app continue.

**Comment by capi** [comment]
@licaon-kter if "w/ no connection" you mean, that you disabled the WiFi module, this is a limitation of Android, you cannot access saved networks while the WiFi module is disabled. A notification toast that you need to enable WiFi should be shown when you select "Restrict to certain wifi networks".

The dialog itself has always been there, this one is not related to "Restrict to certain WiFi networks". Having the restriction set to WiFi, enabling mobile data won't make any difference, since it is still not allowed to access the mobile connection and not starting the syncthing binary is the only way to prevent network traffic from occuring. A side-effect of this is unfortunately, that also means that you cannot modify any of the configuration, since this is done via the API of the native binary, which is not started in this case.

**Comment by licaon-kter** [comment]
Umm, ok. 

Although I still feel this is a serious limitation/bug as the settings (and the folders, devices are settings too) should be available to edit no matter the internet connection status.

**Comment by licaon-kter** [comment]
I've got notifications on but blocked, hence I won't see the toast, thanks for the heads up.

Why would this restriction start just now?

**Comment by Nutomic** [comment]
We can probably just disable the check for internet connection. However, if you have mobile data and connect to a wifi without internet (as detected by Android), that wifi won't be used by Android. It is possible to use wifi explicitly, but I don't know if/how that can be done from Go.

**Comment by licaon-kter** [comment]
And another issue related.

While you can access settings, `Experimental settings` are greyed out and you can toggle them.
