### ISSUE TITLE
Android 2.2 Froyo support revival

### ISSUE THREAD

**Issue by tlaurion** [syncthing/syncthing-android#564]
Hey.

Would it be possible to revive Android 2.2 support?

Would be perfect for Nook Simple Touch with Glowlight as this ebook reader is rootable and is still the best ebook reader around.

Let me know if it would be hard, if challenges to face, accordingly. Would be willing to help as this client is headless and seem the most practical for offthegrid file sync with privacy,

Keep up the good work.
Regard.

**Comment by Nutomic** [comment]
Copying my response from #541: 
>It would be  rather easy to make a "legacy" version of the app that supports older Android versions. Basically, you'd have to remove the whole Android GUI, and just leave the web GUI in.
>
> I'm not interested in maintaining that, but let me know if you want to do it.

**Comment by tlaurion** [comment]
Sorry for duplicating, didn't remembered I actually opened a ticket.
Yeah, I would be interested.

Would it be possible to have a build that just deactivate such features for 2.2?
Can you pinpoint where and how I could do that? Or pinpoint to me a commit that actually worked for 2.2 So I can work y way up to creating such a build?

Please give me a bit of information, since i'm not that used to android development.

**Comment by Nutomic** [comment]
First, set up a build environment by following the instructions in the Readme, so you get a working app. Then, change the AndroidManifest.xml so that the app starts into WebGuiActivity instead of MainActivity. Change the minSdkVersion in build.gradle to your desired value. After that, either use `./gradlew lint` to remove all code that isn't supported on that platform, or run a code analysis in Android Studio and delete all dead code.

If you have any questions, it's probably best if you ask in the forum or on IRC.
