### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: 0.7.8.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [syncthing/syncthing-android#567]

**Comment by Nutomic** [comment]
Can you just open an issue at [F-Droid](https://gitlab.com/fdroid/fdroiddata/issues)? The link is [this one](https://github.com/syncthing/syncthing-android/releases) for Syncthing, and [this](https://github.com/Nutomic/ensichat/releases) for Ensichat.

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by Nutomic** [comment]
What do you want to say with that link?

**Comment by locutis-of-borg-1999** [comment]
You don't maintain the F-Droid repo's for your own projects?

**Comment by licaon-kter** [comment]
Nope, they cater to the Google Play store app only.
F-Droid just pulls it when [releases](https://github.com/syncthing/syncthing-android/releases) appear.
The changelog link should point to [https://github.com/syncthing/syncthing-android/releases/tag/VERSION](https://github.com/syncthing/syncthing-android/releases/tag/0.7.8)

**Comment by Nutomic** [comment]
@locutis-of-borg-1999 App developers don't maintain any repo for F-Droid. That repo is at [fdroiddata](https://gitlab.com/fdroid/fdroiddata). App developers can only edit that data through pull requests, like everyone else. 

Instead of opening issues at tons of projects, it would be much more productive if you would just edit the [metadata](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata) and made merge requests.

**Comment by Nutomic** [comment]
@licaon-kter We definitely cater to F-Droid, I use that version myself ;)

And the correct link is the one I posted above, because F-Droid only supports one changelog per app (not a seperate one for each version).

**Comment by licaon-kter** [comment]
Cater sounded harsher than I meant, aka not build it yourself and/or not hosting a (separate) F-Droid repo. :)
