### ISSUE TITLE
Move "Quit" menu item to the top

### ISSUE THREAD

**Issue by tomtom** [syncthing/syncthing-android#571]
Since the side-bar menu now has an additional "Restart" item, the "Quit" item is moved off the visible area, which could cause irritation. One may assume that on android devices, users won't leave syncthing running all the time. Thus, users are more likely to quit syncthing than to restart it. I'd argue for moving the "Quit" item up so that it's always visible ever on smaller screens.

**Comment by Nutomic** [comment]
I agree that the exit button should always be visible, but putting it at the top feels wrong to me.

Does anyone have an idea how to achieve this in a different way?

**Comment by wweich** [comment]
The quit button is only visible if _run in background_ is disabled. Do we really need a restart button in that case? Instead of _restart_, you can use _quit_ and start the app again.

**Comment by Nutomic** [comment]
It really depends on the screen size. On the Nexus 5, only the exit button doesn't fit. But on my G4, there's plenty of space left.

**Comment by veniosg** [comment]
Why not stick it below settings? This is the standard way of anchoring
options and it arguably makes sense for exit to be there.

**Comment by Nutomic** [comment]
Right, I didn't think of that. Will implement it that way.

**Comment by wweich** [comment]
You could also make some room, by moving the "share device id" item.
I don't know how it is on different screen sizes, but on my Moto X (5.7", QHD) and Nexus 5 (4.9", FHD) the new "copy to clipboard" icon next to the device id at the top, causes the device id to nee more height (one more line wrap) and there is enough space to place a second icon.
So you could place the share icon there instead of giving it a separate menu item.
