### ISSUE TITLE
Incomming folder share notifications are truncated

### ISSUE THREAD

**Issue by wweich** [syncthing/syncthing-android#614]
The notification for "incomming" folder shares are truncated and cannot be expanded.

![screenshot_20160413-144341 01](https://cloud.githubusercontent.com/assets/1026763/14494138/8dc4d5b0-0189-11e6-9408-be78a1d28f64.png)

**Comment by ACinnamonUserInUK** [comment]
I have this problem (incoming folder share notifications are truncated and unexpandable so unreadable) too. Consequently it is hard to troubleshoot other problems with Syncthing on Android - because I do not know what i am telling / allowing the device to do.

Syncthing 0.13.0
Syncthing-Android 0.7.18
