### ISSUE TITLE
after root permission ,super SU can't work

### ISSUE THREAD

**Issue by johnny1996** [syncthing/syncthing-android#639]
the syncthing is conflict with super SU .when i root syncthing. the Super SU can't work.
Whatever the super SU works,the syncthing can't using SD card.

Super SU:2.7.1 
OS:  CM 13
phone: moto G(2015)

**Comment by capi** [comment]
@johnny1996 If I understand that correctly, you cannot use SD card when using root via Super SU. This may be related to the "mount namespace separation" option in Super SU. Try disabling that. This at least helps with programs like Titanium Backup.

Best case would be to try to avoid root with Syncthing, though, because a lot of problems may appear. This is a highly dangerous option.

**Comment by johnny1996** [comment]
@capi thanks a lot. the way is useful.
