### ISSUE TITLE
Same share folder notification displayed multiple times

### ISSUE THREAD

**Issue by alihammadraza** [syncthing/syncthing-android#679]

**Comment by Nutomic** [comment]
I'm not sure what you mean, can you explain it more clearly? Maybe it is #672?

**Comment by cedardocster** [comment]
I get the same thing: android client says "device M17 Laptop wants to share folder phone shares (id number)", I pick the folder to share, save and restart syncthing and within a minute it asks again the same thing.  Also I select a second computer (the one I'm currently using) to share in the android syncthing settings, but when the subsequent repeat question comes back that second computer share is not selected

**Comment by WillMorhler** [comment]
I am having approximately this same issue.  Sharing between two devices - an Android phone currently running 14.39 and a raspberry pi/raspbian running 14.40.  The phone repeatedly gives the notification device [ras pi] wants to share folder [folder].  This is the only folder I am sharing to the phone.  Happy to provide further info that would assist in diagnosing, particularly to determine if this is a bug or user error.

**Comment by Catfriend1** [comment]
I think this happens due to https://github.com/syncthing/syncthing-android/blob/7e3c6c0b8f8bbdc1788d9e0ea7aecadd851862e6/app/src/main/java/com/nutomic/syncthingandroid/service/EventProcessor.java#L120 where we call the addfolder dialog if the user clicks on the notification but do nothing (no report back to syncthing) if the user chose "ignore folder". I guess we need to post some REST on dismissal.

**Comment by Catfriend1** [comment]
Related: https://forum.syncthing.net/t/unexpected-continuous-devicereject-events-from-the-api-with-incrementing-ids/11800

**Comment by Catfriend1** [comment]
Commit https://github.com/Catfriend1/syncthing-android/commit/36fa58a9c814b5feac597d84d7ecc7658ff0e220 fixes the creation of duplicate notifications about the same thing. It adds the device name instead of the device id for better readability. Notification logic for device, folder accepts is moved to NotificationHandler class.

**Comment by Catfriend1** [comment]
This problem also applies to device connection consent notifications.
Also fixed by PR #1177

**Comment by Catfriend1** [comment]
@alihammadraza @cedardocster  @WillMorhler 
I've fixed this bug. Can you please test the debug build available at https://build.syncthing.net/repository/download/SyncthingAndroid_Build/23761:id/outputs/apk/debug/app-debug.apk and report back if it now works correctly?
Please note: This is a debug build and may cause problems. In case you want to be safe, please backup your syncthing configuration and data first.

**Comment by WillMorhler** [comment]
Thanks for the follow up and fix.  Unfortunately, I'm not able to test the debug build but I do appreciate  your efforts.

**Comment by xor-gate** [comment]
Its weird we have to solve this kind of event silencing in all wrappers (webgui, syncthing-android, syncthing-macosx, etcetera) and it is not in the core accessable from the REST API. @AudriusButkevicius and @calmh  should I open a issue/feature request for syncthing daemon to control it?

**Comment by AudriusButkevicius** [comment]
I think (not sure) there is already one, essentially having and endpoint that lists pending invites. This way we don't have to rely on the events not rolling off.

**Comment by xor-gate** [comment]
Probably you are pointing to this one: https://github.com/syncthing/syncthing/issues/4084
