### ISSUE TITLE
Syncthing-android updates file modification times on initial sync

### ISSUE THREAD

**Issue by lfam** [syncthing/syncthing-android#69]
I am having an issue where Syncthing-android resets file modificaiton times to the time of initial sync on the Android device. These modification times are propagated through the cluster. I consider this a data loss.

My cluster consists of four machines:
android 0.4.3 syncthing v0.8.20 (this project)
darwin-amd64-v0.8.21
linux-armv7-v0.8.21
linux-amd64-v.0.8.21

Here is how I reproduce this bug.

I stop syncthing on every machine in the cluster. I ```rm ./*``` from within the repo directory on each machine. Now the repo exists but is completely empty. Then, I ```rsync -a``` my files into the repo of one machine (specifically, the darwin v0.8.21) from a backup. These files have diverse modification times.

When I start the cluster without the android machine, the files sync normally, propagating the correct modification times to each machine in the cluster.

When I add the android machine with an empty repo, it syncs the files from the cluster to itself, but it erroneously updates the modification time of the received files to the present time. These updated modification times are then propagated to the rest of the cluster.

Modification times are important information to me and I don't think it's normal behavior to update them when syncing.

Please let me know if I can provide any logs or debug traces to assist you.

**Comment by AudriusButkevicius** [comment]
So this is not solved because updating mtime does not work in the sdcard, only in the built-in storage, hence the issue.

Unless someone can prove my argument wrong?

**Comment by Nutomic** [comment]
Right.

We once talked about having a database of change times within syncthing. But I suppose this wasn't implemented yet (and may also not be worth the effort).

**Comment by calmh** [comment]
It is probably worth the effort, there's been some thinking and I think we'll implement it somehow soon. But no, not there yet.

**Comment by pmontrasio** [comment]
I got here because I have a related problem and discussing it here might help finding a common solution.

I sync a collection of almost 50k small files (2.90 GB) to a Galaxy S2 (Android 4.0.3) and a Galaxy Tab S 8.4 (Android 4.4.2). I add about 50 new files per week to the collection on my PC (Ubuntu 12.04) and sync them to the internal storage of the two mobile devices. The PC is the folder master.

All is well on the tablet but there is something that changes the modification times of files on the phone (maybe some system indexing process) so the PC ends up sending more than half of the files to the phone every week. I'd love a per folder option to ignore the modification time. This might mean that changes that don't alter the size of the files would go unnoticed (I didn't check the algorithm) but that would be OK for me in this scenario. The database of change times would be a better solution but (maybe) harder to implement.

**Comment by TiZ-EX1** [comment]
I have a problem that may or may not be tangentially related, so I would like to check in here before opening a new issue. Syncthing on my Android device (rooted S4, 4.4.2) has a tendency to push old files and overwrite newer files. Does that have any relation to this issue?

**Comment by Zillode** [comment]
@TiZ-EX1 yes, it does

**Comment by TiZ-EX1** [comment]
Thanks. I'll be watching this issue closely, then.

**Comment by Nutomic** [comment]
This should be fixed in 0.6.1
