### ISSUE TITLE
App closed by OxygenOS

### ISSUE THREAD

**Issue by LeNouveau** [syncthing/syncthing-android#714]
Hi, 

I would like to have Syncthing working only while the phone is charging, but if I clean processes with OxygenOS, Syncthing doesn't start anymore. 
It's pretty anoying, I'm never sure Syncthing will start again. 
I checked I OxygenOS options but could not change this behaviour. 

After some tries, it is this button who defenitively kills Syncthing : 
![screenshot_20160802-205022](https://cloud.githubusercontent.com/assets/3670305/17341387/a1ee89c4-58f4-11e6-87c3-cd12452c5598.png)

Phone : OnePlus 3
OS : Android 6.0.1 + OxygenOS 3.2.2 (Build ONEPLUS A3003_16_160725)
Syncthing : v0.14.3
Syncthing Android : v0.8.1
Not rooted. 

I know, you can probably do nothing about this point, never know. ^^

**Comment by Nutomic** [comment]
Did you try [these things](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#why-is-syncthing-stopped-after-some-time) in the FAQ?

**Comment by LeNouveau** [comment]
Not working :(

Looks like it's not close because of inactivity, but because I ask to close all applications. I would like to close "all, but Syncthing".
Did not find any menu to configure this behaviour, other than the one in FAQ.

**Comment by AudriusButkevicius** [comment]
Well there is not much  we can do here, given the feature is provided by the os?

**Comment by LeNouveau** [comment]
It's the feared response. ^^'

I'm trying my luck with their support at the same time, I'll see if they can do anything.

**Comment by Nutomic** [comment]
Can you check if there's anything in the logs? I use the force stop button in system app info all the time for Syncthing, and it doesn't make any problems. So that button must be doing something weird.

**Comment by capi** [comment]
@LeNouveau The mentioned button stops all processes and background services and prevents a restart of services that returned (like Syncthing) `STICKY` until the application is manually started again. Unfortunately this is a custom patch of OxygenOS and nothing that we can work around.

I personally don't recommend using such features on Android, as it massively interferes with the life-cycle model and memory management of Android applications. Unfortunately, a lot of people want such features and get bitten by the side-effects. And yes, there are a lot of Android apps that don't behave well as well, that's why the need for such features arises in the first place.

**Comment by LeNouveau** [comment]
@Nutomic Do you refer to any Syncthing's log file, or debug output of the phone ? 

@capi I understand this response. 
But when I was on Zenphone2, there was a similar functionality and I was able to say "don't close Syncthing". So, I'm looking for the same possibility on my new phone. 
Obviously, the problem is on OxygenOS side. :/

**Comment by Nutomic** [comment]
@LeNouveau We don't need the logs any more, as capi explained what's happening. As for your issue, you should probably ask on the OxygenOS forums how to solve your problem.
