### ISSUE TITLE
Notification types should depend on foreground service state

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#715]
As of 0.8.1

If Experimental/Foreground is disabled (this is how it looks now):
* Normal
* Low Prio
* None

If Experimental/Foreground is enabled (there is no None as a Notification is needed for the foreground service anyway):
* Normal
* Low Prio (activated by default)

**Comment by Nutomic** [comment]
So you mean that "run in foreground" should work without notification? That's unfortunately not allowed by Android.

**Comment by licaon-kter** [comment]
Umm no, I commented on #694 before.

Again:
* without Foreground you can have 3 states: Normal/Low/None
* with Foreground you can have (as Android dictates) ONLY 2 states: Normal/Low

The UI does no reflect this now, meaning, Foreground ON can coexist with Notification NONE **although** you will have an actual LOW prio notification.

Not sure how to rephrase this...

**Comment by Nutomic** [comment]
Ah I see. So you suggest that the "None" option should be removed if "run in foreground" is checked, right?

**Comment by licaon-kter** [comment]
Yep, and make Low checked (since it's a LOW prio notification by default).
I've said this [before](https://github.com/syncthing/syncthing-android/pull/694#issuecomment-231844151) but was not understeed then either. :P

**Comment by capi** [comment]
I basically agree with that. I still want to argue, that the current solution, which forces "Low" when enabling "Foreground Service" without actually changing the setting, has it's advantages. Since Foreground is still experimental and notification not, I'd not mess to much with it, because, what's the expected state of the setting in the following sequences of interactions?

Case 1:
1. Notification: None
2. Enable Foreground Service (Notification will now be "Low")
3. Disable Foreground Service: Notification will now be "Low" or "None"?

Case 2:
1. Notification: Low
2. Enable Foreground Service (no change to Notification level needed)
3. Disable Foreground Service. What's the state of the notification level now? I'd say "low".

Case 3:
1. Notification: None
2. Enable Foreground Service (Change level to "low")
3. Change Notification to "High"
4. Change Notification level back to "low" (because "none" is not available)
5. Disable Foreground Service. What's the state of the notification level now?

It would require us to keep track what the setting was _before_ enabling the Foreground Service and switching back? What if the setting is changed while Foreground Service is enabled (case 3)?

Another reason I'd leave it the way it is now, is that I am currently thinking about an improvement where `startForeground()` is only called while actually transferring data, and disabling it as soon as everything is in sync, thus being less disruptive as it is now. This would be more complicated if taking your proposal into account, because how to handle the notification settings then?

**Comment by licaon-kter** [comment]
Leave it like this but edit [run_as_foreground_service_summary](https://github.com/syncthing/syncthing-android/blob/dd7966a2280c5b4e3ef001408100caaf00706bc2/src/main/res/values/strings.xml#L305) string and add:
`A low priority notification will be shown, this is an Android requirement.`

**Comment by capi** [comment]
Good idea, will make the according change to the summary.

(*Off-topic:* Regarding the idea about limiting `startForeground()`: it's killed because it's using too much background activity. So by switching it to foreground while it is active I think this should not be triggered. But as I said, just an idea I have in mind for trying. It's entirely possible that the sequence `idle (background) -> Watchdog Check -> busy (foreground) -> idle (background) -> Watchdog Check` might still cause it to be restarted because the watchdog only noticed it as idle and still sees huge CPU consumption. Unfortunately the code of the watchdog I am battling against (OxygenOS) is not released (at least I don't know where), so I don't know how "intelligent" it is.)
