### ISSUE TITLE
Bypass TOR for local LAN traffic

### ISSUE THREAD

**Issue by go2null** [syncthing/syncthing-android#730]
Pull Request #724 implemented an option to tunnel all traffic through Tor (per issue #589).

I have a setup where I do large file syncing on my local LAN to my NAS. In this case, if I want to use Tor for the small file syncing when I'm not home, then will I also be sending my large files over Tor as well?

Note 1: my NAS is setup on my mobile as a local IP address.
Note 2: I enabled Tor option, and my NAS address is still shown as local, so I guess local IPs don't get routed through Tor? Only devices with *dynamic* addresses?

**Comment by Nutomic** [comment]
Ping @calmh @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
Proxy is only used for outgoing connections. Incoming connections will still come through a plain network. 
Also local discovery in not influenced by the proxy, so you still make announcements on the local network, yet when you try and dial someone on the local network, you still go through the proxy. Yet in this specific case I suspect the NAS is commecting to you rather than you to the NAS.

There is a no_proxy env var which is a comma separated list of ips, wildcard hostnames and cidrs which would bypass the proxy when dialing.
