### ISSUE TITLE
Option to run Syncthing even if battery saver mode is on

### ISSUE THREAD

**Issue by nigelinux** [syncthing/syncthing-android#741]
I just found that the problem "Syncthing is disabled" can occur if I turn on built-in battery saver mode on my HTC E8 (I always turn it on for lower screen brightness and CPU usage).

I hope there should be an option to allow the use of Syncthing even in battery saver mode, of course such option should be off by default.

Or at least, the pop-up should show why Syncthing is disabled.  See #729

**Comment by nigelinux** [comment]
#737

**Comment by Ferroin** [comment]
The only way I see this being possible is if Syncthing ignores global sync state, and even then it probably won't work very well.

I agree though that the popup should show a reason that Syncthing is disabled, and ideally, there's no reason that certain settings outside of the app settings shouldn't be accessible even without Syncthing itself running (reading the Device ID shouldn't need Syncthing running for example).

**Comment by nicolas973** [comment]
Hi,
Same problem here (app version 0.8.3 / Samsung Galaxy S5 / Android 5.1.1)

* When "battery saver mode" is on, I always get the "Synthing is disabled" message, even if the battery if fully charged, and even if the phone is plugged into A/C.

* If it can be of any help, I've noticed that Syncthing appears as an active process even though opening it gives the "Syncthing is disabled" message (however it still appears as "disconnected" to other devices)
![whatsapp image 2016-09-17 at 17 29 38](https://cloud.githubusercontent.com/assets/22264564/18611059/6ed25c2e-7cfc-11e6-8161-a5721fd2416d.jpeg)

* Turning "battery saver mode" off did solve the problem for me.

* Disabling Battery Optimization had no effect.

* Enabling "Run service with foreground priority" from the "Experimental" section had no effect.

**Comment by capi** [comment]
It's not a "problem", it was introduced as response to request #603 by c1d5bcc4cdb02eb40ab60030f304515682ba4ba3. But we get so many complaints, that we should make this a configurable option.

**Comment by lugrinder** [comment]
Same problem on HTC One M8 with Android 6.0 and app 0.8.6.

**Comment by fcauwe** [comment]
Same here on a galaxy s2, I got the message 'Syncthing is disabled' with the possibility to check the settings, I checked 5 times before I decided to check the github bugtracker. The message is not clear imho.

**Comment by seakintruth** [comment]
I had nearly given up on running Syncthing on my HTC M9/android 6.0/app 0.9.6, after several months of occasionally editing settings, force stopping, uninstall/reinstall, I finally found mention of this 'Battery Saver' being the culprit. 

I don't have a problem disabling it durring sync, it's just not something I thought of and there was no indication from the app that this could be the problem.

Add a 'Known Causes' link to the 'Syncthing is disabled' message next to 'Change Settings'?

**Comment by Ferroin** [comment]
So, just another couple thought on this: 
1. Battery saver mode was not designed to be the regular operation mode for an Android system, it exists to be used when you absolutely _have_ to make the phone run as long as possible without needing charging, or when the battery gets critically low (the default trip point for it turning on in stock Android is about 5% remaining charge IIRC).  If you actually need to use this to get a full day's run time out of your phone, you have other issues with software or hardware on your phone and should be looking into what's draining it's battery so fast, not just enabling battery saver mode and then trying to force specific applications to ignore it.
2. The message about Syncthing being disabled is too ambiguous, but that issue is somewhat orthogonal to this one, and is largely covered by #729

**Comment by K1773R** [comment]
using your device with power saver always on is a perfect valid use-case. theres the difference between power saver and extreme power saver (here syncthing obviously wont work and this is not related to this mode).

**Comment by K1773R** [comment]
thanks
