### ISSUE TITLE
Feature: Allow to select GUI language explicitly

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing-android#742]
Not just the auto-detected one.

**Comment by Nutomic** [comment]
I've seen this in some apps, but don't understand it. Why don't you just change the language in Android?

**Comment by capi** [comment]
Sometimes I'd like that for apps that are translated very badly from English. I hope, that's not the reason for this request, though. :)

In Google Maps I'd really like that, since the navigation voice is quite challenged by German street names.

**Comment by vladipus** [comment]
If some strings are not translated, the app looks ugly. If you got used to some language version you don't want to forcefully go back.

**Comment by licaon-kter** [comment]
@vladipus Just fix them: https://www.transifex.com/syncthing-android/syncthing-android/

**Comment by m-reiter** [comment]
+1 on that from me, I just wanted to open this request myself. Changing the language in Android is not an option for me since I like to have e.g. my PIM stuff in my native language. However, with technical apps like syncthing, I have to mentally translate some terms back into English anyway to understand what is meant, since english terms are well established and widely used where computers are concerned.

**Comment by m-reiter** [comment]
Great, thanks for implementing this!

**Comment by yukinakato** [comment]
Thanks for this function, however, it doesn't seem to work on my device :( Example below I want to change it from system language Japanese to English but selecting any language doesn't take effect. Is this a device-specific issue...?

![test](https://user-images.githubusercontent.com/22708232/30603129-8c9df6fc-9da1-11e7-9661-724205ef9297.gif)

**Comment by Nutomic** [comment]
@yukinakato Have you tried restarting the app, or your phone? What Android version are you using? Logs might also be useful.
