### ISSUE TITLE
Device is online but not syncing

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#825]
I am using the latest Fdroid version 0.9.3 on Lollipop

The app is open but not sycning anything at all. I tried multiple restarts, phone restart etc without success. 

The adb log shows alot of D/WifiWatchdogStateMachine( 3484): isPackageRunning - top:com.nutomic.syncthingandroid.activities.MainActivity

I also see no syncing activity in the android log at all. Not sure what is going on ;(

https://paste.debian.net/hidden/acf60927/

**Comment by licaon-kter** [comment]
Device? Android version? Ever enabled root mode? Syncing from internal storage or SD card?

**Comment by gerroon** [comment]
Samsung Note, Lollipop, not using the root mode. It is in mixed node. The device is rooted.

**Comment by vioan** [comment]
I have the same issue, the sync from my android 6.0 patch 2016-07-01 (LG G4) to my NAS (FreeBSD) both with syncthing 0.14.21 is not working anymore. It says: Syncing 0%. Nothing changed in folders/config.

**Comment by wweich** [comment]
@vioan How do you run Syncthing on your phone? There is no Syncthing Android App version with Syncthing 0.14.21.

**Comment by vioan** [comment]
sorry, I was wrong, the version on my NAS is 0.14.19:
# syncthing -upgrade-check
09:37:46 INFO: Upgrade available (current "v0.14.19" < latest "v0.14.21")

and on my android is: 0.14.18

**Comment by vioan** [comment]
@wweich I just applied a new update from Play Store on my android, version is the same 0.14.18 and now the sync completed. On my NAS I still have 0.14.19 as mentioned above.

Do you think I should upgrade to 0.14.21 on my NAS, and the sync will still work?

**Comment by Nutomic** [comment]
Yes it will probably fix your problem.

**Comment by wweich** [comment]
If you upgraded your Android version then you downgraded the syncthing version ;).
There was a problem in version 0.14.19, which caused only ARM64 to not sync. So the newest Android App version now uses 0.14.18.
Upgrading your NAS to the newest version won't make a problem.

**Comment by vioan** [comment]
@wweich thanks a lot. I will upgrade my NAS to the newest version.

**Comment by jmbowman** [comment]
I'm seeing very similar behavior on my LG V20, syncing to my Mac; the Mac shows "Syncing (91%)", but no network traffic.  My photos share is listed on the Mac as "Up to Date" and the web UI accurately shows the number of photos on the phone and when the last change was made, but it has actually only fetched 11 of the 72 files (and none during any of my syncing attempts since late November).  The phone lists the folder as Idle, and says that 34 out of 72 files have been synced.  It shows the overall status with the Mac as "Syncing (50%)", but no bytes being transferred.

I'm currently running 0.14.23 on the Mac and 0.9.6 on the phone, but I've had the same problem with the past few versions.  There are a few folders it's accurately and promptly syncing, but others it's just not making any progress on at all.

**Comment by licaon-kter** [comment]
Pressing "override" or "re-scan" in the WebUI does not help?

**Comment by jmbowman** [comment]
There's no "Override Changes" button visible (I had to look in the documentation to discover that existed), and neither "Rescan" nor "Rescan All" seems to have any effect.  Basically, the Mac seems to realize that it isn't fully synced overall, but thinks that each individual folder is.

Screenshot of the UI on the Mac: https://dl.dropboxusercontent.com/u/4804331/syncthing_bug.png

It seems to think that having 72 files and 3 subdirectories makes it up-to-date, although I only count about 60 files (most of which are thumbnails in a hidden folder) and there are many photos on the phone which haven't been copied over.  The total size is accurate according to Finder.  It looks like it has been diligently syncing the thumbnails (46 of them) over time, but hasn't synced any of the actual photos since the first 11 of them.

**Comment by licaon-kter** [comment]
I meant in Android Web UI

**Comment by jmbowman** [comment]
Ok, the Android Web UI *did* show the Override Changes button, and clicking that (on 2 different folders) seems to have gotten them back in sync.  I noticed that opening the photos folder in File Manager on the phone updated the thumbnails and got them out of sync again, so I had to override again after that; I should probably see if I can get it to exclude those.
