### ISSUE TITLE
Open folder crashes on Android 7

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#831]
The same problem as here: http://stackoverflow.com/q/38200282

The suggested solution is to use a FileProvider, but I'm not sure if that makes sense in our case (opening a file manager). Alternatively, we can set the vm policy to not crash when we share the path: http://stackoverflow.com/a/40674771

**Comment by DrSchnagels** [comment]
Heads up from the other post about this issue. PaulAnnekov posted there:
"Bad thing is resource/folder is supported by 1-2 apps from top 20 file managers :(. Most of the managers support only ACTION_GET_CONTENT, which is not what we need."

**Comment by Nutomic** [comment]
Yeah saw that, but not sure what to do about it. Suggestions welcome!

**Comment by PaulAnnekov** [comment]
Maybe try to use embedded file manager like this one http://www.openintents.org/filemanager/ ?

> The OpenIntents file manager allows you to browse your SD card, create directories, rename, move, and delete files. It also acts as an extension to other applications to display “Open” and “Save” dialogs.

**Comment by Nutomic** [comment]
I thought the purpose of this button was to open the user's preferred file manager? So it would make the whole feature less useful. Maybe we could use that as a fallback if the intent fails?

**Comment by PaulAnnekov** [comment]
@Nutomic that's a good feature, but each version of Android tries to abstract user from filesystem more and more. Yep, we can do it as a fallback, but I'm sure it will be used in 95% cases, because only 1-2 file managers support this intent. Can we collect some stats?

**Comment by Nutomic** [comment]
Wie dont have any usage tracking in the Android app. Maybe a poll on the forum?

**Comment by PaulAnnekov** [comment]
Of course it's better to have real metrics from all users, because forum poll doesn't represent all users group. But if we don't have such feature, then we can use forum as a fallback. Probably it should look  like this:
Is your favorite file manager supported by "Open folder" button in the app?
- Yes
- No (also if you don't use file managers)

Would you mind if Open folder button will open internal file manager instead of trying to find supported in your system?
- Yes (I against this idea, want to use my external file manager and it's supported now)
- No

Suggest, correct, post in the forum :).

**Comment by Nutomic** [comment]
One thing to consider is that we also can't open any file manager on Android 7 (due to the stuff I posted in the op). Also, you should probably add options "I don't care" for each question. You can just post it on the forum yourself ;)

**Comment by PaulAnnekov** [comment]
https://forum.syncthing.net/t/poll-open-folder-button-and-file-managers/9067
