### ISSUE TITLE
"Save to Syncthing" could remember last folder

### ISSUE THREAD

**Issue by JohnVeness** [syncthing/syncthing-android#899]
At the moment, every time you go into the "Save to Syncthing" window it defaults to the first listed share. It would be very useful if it could remember the last share that was saved to.

If issue #898 is implemented, this would include remembering the last subfolder saved into.

**Comment by jmintb** [comment]
Should it remember the last subfolder for all of the Syncthing folders or just the most recent one?

**Comment by JohnVeness** [comment]
Good question. I think the average used would expect at the very least by default for it to remember the last subfolder used in the last Syncthing folder used. But yes, it might be a nice addition if, if at this point the user picked a different Syncthing folder, that it remembered the last subfolder used in that Syncthing folder too.

**Comment by jmintb** [comment]
I am also considering adding a button that clears the saved subdirectory so that you can easily get back to the main folder that is being synced, without having to navigate back to the top of the folder hierachy.
What do you think?

**Comment by JohnVeness** [comment]
Well if you're considering how to navigate back up the folder tree, I'm a fan of "clickable breadcrumbs", where a single click can navigate instantly up to any parent or grandparent, up to the top level.

**Comment by jmintb** [comment]
Well I was thinking outsite of the file navigation ui. If you want to share something to the synced folder, but last time you added a file to it you had navigated to a sub directory. Then instead of opening the file browseing ui, you press the button and the saved sub directory is cleared. Something like this: 
Before button press:
![screenshot_20170816-215321](https://user-images.githubusercontent.com/10332534/29382674-a28e2d22-82cd-11e7-8532-c8f7cd3a5bb3.png)

After button press:
![screenshot_20170816-215326](https://user-images.githubusercontent.com/10332534/29382698-bd048264-82cd-11e7-8695-cad9fd30dab4.png)

**Comment by JohnVeness** [comment]
Oh I see. I was rather thinking that as soon as you entered the "Save to Syncthing" window, you would be presented with a folder browser, with a box for the user to modify the filename. You could then browse within the folders, with the top-level being all the Syncthing folders.

I realise this model contradicts my idea of remembering the last used subfolder of each Syncthing folder, because it would seem strange to the user if they jumped further down the tree when clicking on one of the top-level folders.

**Comment by Nutomic** [comment]
The "Clear subfolder" button is way too complicated, and might be hard to understand. Its totally fine to use back navigation in that case.
