### ISSUE TITLE
Remote Control by Broadcast-Intent is still broken (v10.0)

### ISSUE THREAD

**Issue by sqrt-1764** [syncthing/syncthing-android#995]
As I can not reopen #976, I have to create a new issue.

Unfortunately this feature still does not work in the current version from Play-Store. (Using Android 8.1)

**Comment by emmercm** [comment]
I believe I'm seeing the same behavior on my Pixel 1 8.1.0, Android app 0.10.5, Syncthing 0.14.45.

Using Tasker to send the broadcasts.

**Comment by cmusik** [comment]
Trying to start the intent on android 8.1 I get this message:

`W BroadcastQueue: Background execution not allowed: receiving Intent { act=com.nutomic.syncthingandroid.action.START flg=0x10 } to com.nutomic.syncthingandroid/.receiver.AppConfigReceiver`

**Comment by Catfriend1** [comment]
@sqrt-1764 @emmercm @cmusik Hi together,
I did a research on this problem and found out that it is not a SyncThing app issue. Android bans sending implicit broadcasts since version 8+ for apps with targetSdk > 25 (We currently use 27.x). The new way of sending the broadcasts correctly is putting the target package name in. So Tasker has to put the name of this app in (com.nutomic.syncthingandroid). The current version of Tasker on the play store (5.2bf1) supports sending the intents correctly. I verified it on Android 8.1 on a i9100 device and it worked. You can find an updated documentation on the wiki at https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents .

**Comment by Catfriend1** [comment]
@acornsirup Which Android version are you on? Did you grant "ignore battery optimizations" to the syncthing-android app?

**Comment by Catfriend1** [comment]
Maybe related to the service start timeout of 5 secs, see issue https://github.com/syncthing/syncthing-android/issues/1192

**Comment by acornsirup** [comment]
Seems like it does, yes.
